Setup initial pages and routing
Yknot-BCS/rec-marketplace-ui pull request #1
Opened 2022-07-20 13:05 UTC by MrMarxz

Added new pages and configured routing for them. The paths for the routes are as follows:

### Devices
- /devices
- /devices/view-device
- /devices/register-device

### Smart Metres
- /smart-metres
- /smart-metres/view

### REC's
- /rec
- /rec/claim
- /rec/active
- /rec/buy
- /rec/sell
- /rec/redeem
- /rec/attributes

### Registry
- /registry
- /registry/approval
- /registry/users
- /registry/devices
- /registry/rec-issued
- /registry/trade
- /registry/rec-redemption

2022-07-22 06:55 UTC, JPBeukes requested changes

2022-07-22 06:55 UTC, JPBeukes commented on .eslintrc.js
> +    "prettier/prettier": ["error", { "endOfLine": "auto" }]
At the moment I prefer to stick with the Linux end of line style, but I'm open for debate. Is the default LF a problem for your Windows editor? Here is a resource I found on the settings, but I still need to read to understand what `auto` does. https://prettier.io/docs/en/options.html#end-of-line

2022-07-22 06:55 UTC, JPBeukes commented on quasar.conf.js
> +      port: 8000,
Let's stick with 8080 for now

2022-07-22 06:55 UTC, JPBeukes commented on src/pages/Registry.vue
> +<script lang="ts">
I think it is worth grouping all of the registry pages into a single folder: `src/pages/registry`. You can still keep the page names RegistrySomething

2022-07-22 06:55 UTC, JPBeukes commented on src/router/routes.ts
> +  //#region START OF ACCOUNT ACCESS ROUTES
Wow, this is an awesome feature :sunglasses:

2022-07-22 10:30 UTC, MrMarxz commented on .eslintrc.js
> +    "prettier/prettier": ["error", { "endOfLine": "auto" }]
So prettier complains when there is an extra open line between code, or even if there is indentation applied to whitespaces. The endOfLine sets prettier to ignore any whitespaces at the end of a line.
It can be removed since it is only a personal preference and does not affect any functionality if removed or added.

2022-07-22 10:31 UTC, MrMarxz commented on quasar.conf.js
> +      port: 8000,
No problem, I forgot to change it since it did not work on my PC on port 8080

2022-07-22 10:34 UTC, MrMarxz commented on src/pages/Registry.vue
> +<script lang="ts">
No problem, I was planning on putting all the route pages into their own folders with appropriate names, since there are over 10 pages. Will just help with the logic of the filing structure.

2022-07-25 09:42 UTC, Dewald928 approved these changes
My only comment is on the name of the Smart Metre. I think it should be Smart Meter?

2022-07-25 09:45 UTC, merged